## Popularity Based Movie Recommendation System

In [1]:
import kagglehub
path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")

Downloading to /root/.cache/kagglehub/datasets/tmdb/tmdb-movie-metadata/2.archive...

100%|██████████| 8.89M/8.89M [00:01<00:00, 6.04MB/s]

Extracting files...

In [2]:
import os
os.listdir(path)

['tmdb_5000_movies.csv', 'tmdb_5000_credits.csv']

In [3]:
import pandas as pd
credits=pd.read_csv(os.path.join(path, "tmdb_5000_credits.csv"))
movies=pd.read_csv(os.path.join(path, "tmdb_5000_movies.csv"))

In [4]:
movies.sample()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1398,35000000,"[{""id"": 28, ""name"": ""Action""}]",http://www.maxpaynethemovie.com,13051,"[{""id"": 782, ""name"": ""assassin""}, {""id"": 41645...",en,Max Payne,Coming together to solve a series of murders i...,25.903237,"[{""name"": ""Dune Entertainment"", ""id"": 444}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-10-15,85416905,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,When a Man Has Lost Everything. He Only has Re...,Max Payne,5.2,613

In [6]:
movies=movies[['title','popularity','vote_average','vote_count']]
movies.head()

,title,popularity,vote_average,vote_count
0,Avatar,150.437577,7.2,11800
1,Pirates of the Caribbean: At World's End,139.082615,6.9,4500
2,Spectre,107.376788,6.3,4466
3,The Dark Knight Rises,112.312950,7.6,9106
4,John Carter,43.926995,6.1,2124

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         4803 non-null   object
 1   popularity    4803 non-null   float64
 2   vote_average  4803 non-null   float64
 3   vote_count    4803 non-null   int64
dtypes: float64(2), int64(1), object(1)
memory usage: 150.2+ KB

In [8]:
movies.describe()

        popularity  vote_average    vote_count
count  4803.000000   4803.000000   4803.000000
mean     21.492301      6.092172    690.217989
std      31.816650      1.194612   1234.585891
min       0.000000      0.000000      0.000000
25%       4.668070      5.600000     54.000000
50%      12.921594      6.200000    235.000000
75%      28.313505      6.800000    737.000000
max     875.581305     10.000000  13752.000000

In [9]:
movies['title'].is_unique

False

In [10]:
movies['title'].value_counts()

title
The Host            2
Batman              2
Out of the Blue     2
Awake               1
Beneath Hill 60     1
                   ..
Drag Me to Hell     1
Southpaw            1
Sicario             1
Glory Road          1
30 Days of Night    1
Name: count, Length: 4800, dtype: int64

In [11]:
m=movies['vote_count'].quantile(0.75)
movies['weighted_votes'] = (
    (movies['vote_count'] * movies['vote_average'])
    / (movies['vote_count'] + m)
    +
    (m * movies['vote_average'].median())
    / (m + movies['vote_count'])
)

In [13]:
movies.sample()

         title  popularity  vote_average  vote_count  weighted_votes
1164  Scream 3   24.992057           5.7         736         5.95017

In [14]:
movies.drop(columns=['vote_average','vote_count'],inplace=True)

In [15]:
movies=movies.groupby('title')[['popularity','weighted_votes']].mean().reset_index()

In [17]:
movies=movies.sort_values(['weighted_votes','popularity'],ascending=False)

In [18]:
movies.sample()

           title  popularity  weighted_votes
1442  Gettysburg    5.529035        6.243531

In [21]:
movies.to_csv('movies.csv',index=False)